Map<String, dynamic> jsonData = {
  "familyMember1": {
    "familyName": {
      "serviceType": "familyName1",
      "visible": true,
      "name": "1st Family Member Name",
      "placeholder": "Enter the Name of the Family Member1",
      "type": "Textinput",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "errorMsg": "Name cannot contain Numbers and Special Characters",
      "pattern": r"^( ?\\.?[a-zA-Z]+)+$",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Name",
      "isError": false
    },
    "familyAccountNumber": {
      "serviceType": "familyAccountNumber1",
      "visible": true,
      "name": "1st Family Member Account Number",
      "placeholder": "Enter Account Number of the Family Member",
      "type": "AccountNumber",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "12",
      "maxText": "Max 12 charcters are allowed",
      "errorMsg": "Please enter Account Number of the Family Member",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Account Number* 1",
      "isError": false
    },
    "familydob": {
      "type": "date",
      "placeholder": "Select DoB of the  Family Member",
      "visible": true,
      "errorMsg":
          "Date of birth does not match with our records. Please enter correct date of birth.",
      "name": "1st Family Member DoB",
      "pattern": null,
      "required": true,
      "value": "",
      "minYear": "1900",
      "maxYear": "2021",
      "serviceType": "familyDob1",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "validation": "past date for issuance date",
      "displayName": "DOB*",
      "isError": false
    },
    "familyRelationship": {
      "type": "dropdown",
      "placeholder": "Select Relationship Type",
      "visible": true,
      "errorMsg": "Please select Relationship",
      "name": "1st Family Member Relationship Type",
      "validation": null,
      "required": true,
      "value": "",
      "Buttonvalues": [
        "Self",
        "Spouse",
        "Father",
        "Mother",
        "Brother",
        "Sister",
        "Child",
        "Father-in-law",
        "Mother-in-law",
        "Son-in law",
        "Daughter-in law",
        "Brother-in law",
        "Sister-in law",
        "Grandson",
        "Grand daughter",
        "Grand Father",
        "Grand Mother"
      ],
      "serviceType": "relationship1",
      "maxLength": "15",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Relation Type*",
      "isError": false
    },
    "familyEmail": {
      "type": "Email",
      "placeholder": "Enter Email Id",
      "visible": true,
      "errorMsg": "Please enter valid Email Id",
      "name": "1st Family Member Email Id",
      "isEmail": true,
      "validation": null,
      "pattern": "",
      "required": true,
      "value": "",
      "serviceType": "email_id1",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "autoFill": true,
      "disable": true,
      "displayName": "Email",
      "isError": false
    },
    "name": "1st Family Member"
  },
  "familyMember2": {
    "familyName": {
      "serviceType": "familyName2",
      "visible": true,
      "name": "2nd Family Member Name",
      "placeholder": "Enter the Name of the Family Member2",
      "type": "Textinput",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "errorMsg": "Name cannot contain Numbers and Special Characters",
      "pattern": r"^( ?\\.?[a-zA-Z]+)+$",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Name",
      "isError": false
    },
    "familyAccountNumber": {
      "serviceType": "familyAccountNumber2",
      "visible": true,
      "name": "2nd Family Member Account Number",
      "placeholder": "Enter Account Number of the Family Member",
      "type": "AccountNumber",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "12",
      "maxText": "Max 12 charcters are allowed",
      "errorMsg": "Please enter Account Number of the Family Member",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Account Number* 2",
      "isError": false
    },
    "familydob": {
      "type": "date",
      "placeholder": "Select DoB of the  Family Member",
      "visible": true,
      "errorMsg":
          "Date of birth does not match with our records. Please enter correct date of birth.",
      "name": "2nd Family Member DoB",
      "pattern": null,
      "required": true,
      "value": "",
      "minYear": "1900",
      "maxYear": "2021",
      "serviceType": "familyDob2",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "validation": "past date for issuance date",
      "displayName": "DOB*",
      "isError": false
    },
    "familyRelationship": {
      "type": "dropdown",
      "placeholder": "Select Relationship Type",
      "visible": true,
      "errorMsg": "Please select Relationship",
      "name": "2nd Family Member Relationship Type",
      "validation": null,
      "required": true,
      "value": "",
      "Buttonvalues": [
        "Self",
        "Spouse",
        "Father",
        "Mother",
        "Brother",
        "Sister",
        "Child",
        "Father-in-law",
        "Mother-in-law",
        "Son-in law",
        "Daughter-in law",
        "Brother-in law",
        "Sister-in law",
        "Grandson",
        "Grand daughter",
        "Grand Father",
        "Grand Mother"
      ],
      "serviceType": "relationship2",
      "maxLength": "15",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Relation Type*",
      "isError": false
    },
    "familyEmail": {
      "type": "Email",
      "placeholder": "Enter Email Id",
      "visible": true,
      "errorMsg": "Please enter valid Email Id",
      "name": "2nd Family Member Email Id",
      "isEmail": true,
      "validation": null,
      "pattern": "",
      "required": true,
      "value": "",
      "serviceType": "email_id2",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "autoFill": true,
      "disable": true,
      "displayName": "Email",
      "isError": false
    },
    "name": "2nd Family Member"
  },
  "familyMember3": {
    "familyName": {
      "serviceType": "familyName3",
      "visible": true,
      "name": "3rd Family Member Name",
      "placeholder": "Enter the Name of the Family Member3",
      "type": "Textinput",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "errorMsg": "Name cannot contain Numbers and Special Characters",
      "pattern": r"^( ?\\.?[a-zA-Z]+)+$",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Name",
      "isError": false
    },
    "familyAccountNumber": {
      "serviceType": "familyAccountNumber3",
      "visible": true,
      "name": "3rd Family Member Account Number",
      "placeholder": "Enter Account Number of the Family Member",
      "type": "AccountNumber",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "12",
      "maxText": "Max 12 charcters are allowed",
      "errorMsg": "Please enter Account Number of the Family Member",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Account Number* 3",
      "isError": false
    },
    "familydob": {
      "type": "date",
      "placeholder": "Select DoB of the  Family Member",
      "visible": true,
      "errorMsg":
          "Date of birth does not match with our records. Please enter correct date of birth.",
      "name": "3rd Family Member Date of Birth",
      "pattern": null,
      "required": true,
      "value": "",
      "minYear": "1900",
      "maxYear": "2021",
      "serviceType": "familyDob3",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "validation": "past date for issuance date",
      "displayName": "DOB*",
      "isError": false
    },
    "familyRelationship": {
      "type": "dropdown",
      "placeholder": "Select Relationship Type",
      "visible": true,
      "errorMsg": "Please select Relationship",
      "name": "3rd Family Member Relationship Type",
      "validation": null,
      "required": true,
      "value": "",
      "Buttonvalues": [
        "Self",
        "Spouse",
        "Father",
        "Mother",
        "Brother",
        "Sister",
        "Child",
        "Father-in-law",
        "Mother-in-law",
        "Son-in law",
        "Daughter-in law",
        "Brother-in law",
        "Sister-in law",
        "Grandson",
        "Grand daughter",
        "Grand Father",
        "Grand Mother"
      ],
      "serviceType": "relationship3",
      "maxLength": "15",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Relation Type*",
      "isError": false
    },
    "familyEmail": {
      "type": "Email",
      "placeholder": "Enter Email Id",
      "visible": true,
      "errorMsg": "Please enter valid Email Id",
      "name": "3rd Family Member Email ID",
      "isEmail": true,
      "validation": null,
      "pattern": "",
      "required": true,
      "value": "",
      "serviceType": "email_id3",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "autoFill": true,
      "disable": true,
      "displayName": "Email",
      "isError": false
    },
    "name": "3rd Family Member"
  },
  "familyMember4": {
    "familyName": {
      "serviceType": "familyName4",
      "visible": true,
      "name": "4th Family Member Name",
      "placeholder": "Enter the Name of the Family Member4",
      "type": "Textinput",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "errorMsg": "Name cannot contain Numbers and Special Characters",
      "pattern": r"^( ?\\.?[a-zA-Z]+)+$",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Name",
      "isError": false
    },
    "familyAccountNumber": {
      "serviceType": "familyAccountNumber4",
      "visible": true,
      "name": "4th Family Member Account Number",
      "placeholder": "Enter Account Number of the Family Member",
      "type": "AccountNumber",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "12",
      "maxText": "Max 12 charcters are allowed",
      "errorMsg": "Please enter Account Number of the Family Member",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Account Number* 4",
      "isError": false
    },
    "familydob": {
      "type": "date",
      "placeholder": "Select DoB of the  Family Member",
      "visible": true,
      "errorMsg":
          "Date of birth does not match with our records. Please enter correct date of birth.",
      "name": "4th Family Member Date of Birth",
      "pattern": null,
      "required": true,
      "value": "",
      "minYear": "1900",
      "maxYear": "2021",
      "serviceType": "familyDob4",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "validation": "past date for issuance date",
      "displayName": "DOB*",
      "isError": false
    },
    "familyRelationship": {
      "type": "dropdown",
      "placeholder": "Select Relationship Type",
      "visible": true,
      "errorMsg": "Please select Relationship",
      "name": "4th Family Member Relationship Type",
      "validation": null,
      "required": true,
      "value": "",
      "Buttonvalues": [
        "Self",
        "Spouse",
        "Father",
        "Mother",
        "Brother",
        "Sister",
        "Child",
        "Father-in-law",
        "Mother-in-law",
        "Son-in law",
        "Daughter-in law",
        "Brother-in law",
        "Sister-in law",
        "Grandson",
        "Grand daughter",
        "Grand Father",
        "Grand Mother"
      ],
      "serviceType": "relationship4",
      "maxLength": "15",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Relation Type*",
      "isError": false
    },
    "familyEmail": {
      "type": "Email",
      "placeholder": "Enter Email Id",
      "visible": true,
      "errorMsg": "Please enter valid Email Id",
      "name": "4th Family Member Email ID",
      "isEmail": true,
      "validation": null,
      "pattern": "",
      "required": true,
      "value": "",
      "serviceType": "email_id4",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "autoFill": true,
      "disable": true,
      "displayName": "Email",
      "isError": false
    },
    "name": "4th Family Member"
  },
  "familyMember5": {
    "familyName": {
      "serviceType": "familyName5",
      "visible": true,
      "name": "5th Family Member Name",
      "placeholder": "Enter the Name of the Family Member5",
      "type": "Textinput",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "errorMsg": "Name cannot contain Numbers and Special Characters",
      "pattern": r"^( ?\\.?[a-zA-Z]+)+$",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Name",
      "isError": false
    },
    "familyAccountNumber": {
      "serviceType": "familyAccountNumber5",
      "visible": true,
      "name": "5th Family Member Account Number",
      "placeholder": "Enter Account Number of the Family Member",
      "type": "AccountNumber",
      "value": "",
      "validation": "null",
      "required": true,
      "maxLength": "12",
      "maxText": "Max 12 charcters are allowed",
      "errorMsg": "Please enter Account Number of the Family Member",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Account Number*5",
      "isError": false
    },
    "familydob": {
      "type": "date",
      "placeholder": "Select DoB of the  Family Member",
      "visible": true,
      "errorMsg":
          "Date of birth does not match with our records. Please enter correct date of birth.",
      "name": "5th Family Member Date of Birth",
      "pattern": null,
      "required": true,
      "value": "",
      "minYear": "1900",
      "maxYear": "2021",
      "serviceType": "familyDob5",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "validation": "past date for issuance date",
      "displayName": "DOB*",
      "isError": false
    },
    "familyRelationship": {
      "type": "dropdown",
      "placeholder": "Select Relationship Type",
      "visible": true,
      "errorMsg": "Please select Relationship",
      "name": "5th Family Member Relationship Type",
      "validation": null,
      "required": true,
      "value": "",
      "Buttonvalues": [
        "Self",
        "Spouse",
        "Father",
        "Mother",
        "Brother",
        "Sister",
        "Child",
        "Father-in-law",
        "Mother-in-law",
        "Son-in law",
        "Daughter-in law",
        "Brother-in law",
        "Sister-in law",
        "Grandson",
        "Grand daughter",
        "Grand Father",
        "Grand Mother"
      ],
      "serviceType": "relationship5",
      "maxLength": "15",
      "isRepeat": true,
      "isPreview": true,
      "displayName": "Relation Type*",
      "isError": false
    },
    "familyEmail": {
      "type": "Email",
      "placeholder": "Enter Email Id",
      "visible": true,
      "errorMsg": "Please enter valid Email Id",
      "name": "5th Family Member Email ID",
      "isEmail": true,
      "validation": null,
      "pattern": "",
      "required": true,
      "value": "",
      "serviceType": "email_id5",
      "maxLength": "45",
      "maxText": "Max 45 charcters are allowed",
      "isRepeat": true,
      "isPreview": true,
      "autoFill": true,
      "disable": true,
      "displayName": "Email",
      "isError": false
    },
    "name": "5th Family Member"
  },
};
